"use strict";
// console.log("itamar");
// רכז (POINT GUARD) – עמדה 1: ...
// קלעי (SHOOTING GUARD) – עמדה 2: ...
// סמול פורוורד (SMALL FORWARD) – עמדה 3: ...
// פאוור פורוורד (Power Forward) – עמדה 4: ...
// סנטר (CENTER) – עמדה 5: ...
